services:
  - type: web
    name: aifindr-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MISTRAL_API_KEY
        value: YOUR_MISTRAL_API_KEY
      - key: MISTRAL_MODEL
        value: mistral-large-latest
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 10